// Public API do Globo Ads Design System.
// Consumidores (ex: apps/simulacrum) importam daqui: `import { Button } from '@globo-ads/ds'`.
// Cada componente é re-exportado como named export (default do módulo) + seus tipos (export *).
// Componentes internos de documentação (components/docs/*) NÃO fazem parte da API pública.

export { default as Accordion } from './components/Accordion/Accordion'
export * from './components/Accordion/Accordion'
export { default as Avatar } from './components/Avatar/Avatar'
export * from './components/Avatar/Avatar'
export { default as AvatarGroup } from './components/AvatarGroup/AvatarGroup'
export * from './components/AvatarGroup/AvatarGroup'
export { default as Badge } from './components/Badge/Badge'
export * from './components/Badge/Badge'
export { default as BadgeCounter } from './components/BadgeCounter/BadgeCounter'
export * from './components/BadgeCounter/BadgeCounter'
export { default as BadgePointer } from './components/BadgePointer/BadgePointer'
export * from './components/BadgePointer/BadgePointer'
export { default as Breadcrumb } from './components/Breadcrumb/Breadcrumb'
export * from './components/Breadcrumb/Breadcrumb'
export { default as Button } from './components/Button/Button'
export * from './components/Button/Button'
export { default as Calendar } from './components/Calendar/Calendar'
export * from './components/Calendar/Calendar'
export { default as MultiDateCalendar } from './components/MultiDateCalendar/MultiDateCalendar'
export * from './components/MultiDateCalendar/MultiDateCalendar'
export { default as Checkbox } from './components/Checkbox/Checkbox'
export * from './components/Checkbox/Checkbox'
export { default as ChipAssist } from './components/ChipAssist/ChipAssist'
export * from './components/ChipAssist/ChipAssist'
export { default as ChipFilter } from './components/ChipFilter/ChipFilter'
export * from './components/ChipFilter/ChipFilter'
export { default as ChipInput } from './components/ChipInput/ChipInput'
export * from './components/ChipInput/ChipInput'
export { default as ChipSuggestion } from './components/ChipSuggestion/ChipSuggestion'
export * from './components/ChipSuggestion/ChipSuggestion'
export { default as Collapse } from './components/Collapse/Collapse'
export * from './components/Collapse/Collapse'
export { default as Combobox } from './components/Combobox/Combobox'
export * from './components/Combobox/Combobox'
export { default as ConfirmDialog } from './components/ConfirmDialog/ConfirmDialog'
export * from './components/ConfirmDialog/ConfirmDialog'
export { default as DatePicker } from './components/DatePicker/DatePicker'
export * from './components/DatePicker/DatePicker'
export { default as DateRangePicker } from './components/DateRangePicker/DateRangePicker'
export * from './components/DateRangePicker/DateRangePicker'
export { default as DateTimePicker } from './components/DateTimePicker/DateTimePicker'
export * from './components/DateTimePicker/DateTimePicker'
export { default as FieldLabel } from './components/FieldLabel/FieldLabel'
export * from './components/FieldLabel/FieldLabel'
export { default as FieldMessage } from './components/FieldMessage/FieldMessage'
export * from './components/FieldMessage/FieldMessage'
export { default as Hyperlink } from './components/Hyperlink/Hyperlink'
export * from './components/Hyperlink/Hyperlink'
export { default as InfoPanel } from './components/InfoPanel/InfoPanel'
export * from './components/InfoPanel/InfoPanel'
export { default as InlineLoader } from './components/InlineLoader/InlineLoader'
export * from './components/InlineLoader/InlineLoader'
export { default as InteractiveCard } from './components/InteractiveCard/InteractiveCard'
export * from './components/InteractiveCard/InteractiveCard'
export { default as Pagination } from './components/Pagination/Pagination'
export * from './components/Pagination/Pagination'
export { default as Radio } from './components/Radio/Radio'
export * from './components/Radio/Radio'
export { default as Select } from './components/Select/Select'
export * from './components/Select/Select'
export { default as Skeleton } from './components/Skeleton/Skeleton'
export * from './components/Skeleton/Skeleton'
export { default as StaticCard } from './components/StaticCard/StaticCard'
export * from './components/StaticCard/StaticCard'
export { default as Switch } from './components/Switch/Switch'
export * from './components/Switch/Switch'
export { default as Tabs } from './components/Tabs/Tabs'
export * from './components/Tabs/Tabs'
export { default as TextField } from './components/TextField/TextField'
export * from './components/TextField/TextField'
export { default as Textarea } from './components/Textarea/Textarea'
export * from './components/Textarea/Textarea'
export { default as TimePicker } from './components/TimePicker/TimePicker'
export * from './components/TimePicker/TimePicker'
export { default as Toast } from './components/Toast/Toast'
export * from './components/Toast/Toast'
export { default as Tooltip } from './components/Tooltip/Tooltip'
export * from './components/Tooltip/Tooltip'
