export type SpacingToken = {
  name: string
  variable: string
  valuePx: number
  valueRem: string
  description: string
}

export const SPACING_TOKENS: SpacingToken[] = [
  {
    name: 'Spacing 000',
    variable: '--spacing-000',
    valuePx: 0,
    valueRem: '0',
    description: 'Valor nulo. Usado para remover espaçamento de um elemento.',
  },
  {
    name: 'Spacing 012',
    variable: '--spacing-012',
    valuePx: 1,
    valueRem: '0.0625rem',
    description: 'Separação mínima. Usada em bordas de 1px e divisores ultra-finos.',
  },
  {
    name: 'Spacing 025',
    variable: '--spacing-025',
    valuePx: 2,
    valueRem: '0.125rem',
    description: 'Espaçamento extra-pequeno. Ajuste fino entre elementos muito próximos.',
  },
  {
    name: 'Spacing 050',
    variable: '--spacing-050',
    valuePx: 4,
    valueRem: '0.25rem',
    description: 'Espaçamento mínimo funcional. Gaps internos de componentes compactos.',
  },
  {
    name: 'Spacing 075',
    variable: '--spacing-075',
    valuePx: 6,
    valueRem: '0.375rem',
    description: 'Separação sutil entre elementos adjacentes dentro de um componente.',
  },
  {
    name: 'Spacing 100',
    variable: '--spacing-100',
    valuePx: 8,
    valueRem: '0.5rem',
    description: 'Espaçamento base. Padding interno de chips, badges e elementos compactos.',
  },
  {
    name: 'Spacing 125',
    variable: '--spacing-125',
    valuePx: 10,
    valueRem: '0.625rem',
    description: 'Gap entre ícone e label em componentes de ação compactos.',
  },
  {
    name: 'Spacing 150',
    variable: '--spacing-150',
    valuePx: 12,
    valueRem: '0.75rem',
    description: 'Padding interno de botões pequenos e espaçamento entre elementos inline.',
  },
  {
    name: 'Spacing 175',
    variable: '--spacing-175',
    valuePx: 14,
    valueRem: '0.875rem',
    description: 'Espaçamento intermediário entre componentes de densidade média.',
  },
  {
    name: 'Spacing 200',
    variable: '--spacing-200',
    valuePx: 16,
    valueRem: '1rem',
    description: 'Espaçamento padrão do sistema. Gap de grade, padding de inputs e botões médios.',
  },
  {
    name: 'Spacing 250',
    variable: '--spacing-250',
    valuePx: 20,
    valueRem: '1.25rem',
    description: 'Gap entre elementos de lista, padding horizontal de menus.',
  },
  {
    name: 'Spacing 300',
    variable: '--spacing-300',
    valuePx: 24,
    valueRem: '1.5rem',
    description: 'Padding interno de cards compactos e espaçamento entre seções menores.',
  },
  {
    name: 'Spacing 350',
    variable: '--spacing-350',
    valuePx: 28,
    valueRem: '1.75rem',
    description: 'Padding vertical de cards de tamanho médio.',
  },
  {
    name: 'Spacing 400',
    variable: '--spacing-400',
    valuePx: 32,
    valueRem: '2rem',
    description: 'Padding padrão de cards e containers de conteúdo.',
  },
  {
    name: 'Spacing 450',
    variable: '--spacing-450',
    valuePx: 36,
    valueRem: '2.25rem',
    description: 'Espaçamento generoso entre grupos de componentes.',
  },
  {
    name: 'Spacing 500',
    variable: '--spacing-500',
    valuePx: 40,
    valueRem: '2.5rem',
    description: 'Padding de áreas de preview e containers de destaque.',
  },
  {
    name: 'Spacing 550',
    variable: '--spacing-550',
    valuePx: 44,
    valueRem: '2.75rem',
    description: 'Espaçamento amplo entre blocos de conteúdo distintos.',
  },
  {
    name: 'Spacing 600',
    variable: '--spacing-600',
    valuePx: 48,
    valueRem: '3rem',
    description: 'Padding de áreas de preview grandes e seções de destaque.',
  },
  {
    name: 'Spacing 700',
    variable: '--spacing-700',
    valuePx: 56,
    valueRem: '3.5rem',
    description: 'Espaçamento entre seções de página e grupos de conteúdo principais.',
  },
  {
    name: 'Spacing 800',
    variable: '--spacing-800',
    valuePx: 64,
    valueRem: '4rem',
    description: 'Margem entre seções documentais e blocos estruturais.',
  },
  {
    name: 'Spacing 900',
    variable: '--spacing-900',
    valuePx: 72,
    valueRem: '4.5rem',
    description: 'Gap padrão entre seções de página de documentação.',
  },
  {
    name: 'Spacing 1000',
    variable: '--spacing-1000',
    valuePx: 80,
    valueRem: '5rem',
    description: 'Padding de páginas e containers de maior hierarquia.',
  },
  {
    name: 'Spacing 1200',
    variable: '--spacing-1200',
    valuePx: 96,
    valueRem: '6rem',
    description: 'Espaçamento de rodapé e separação entre blocos de nível superior.',
  },
  {
    name: 'Spacing 1600',
    variable: '--spacing-1600',
    valuePx: 128,
    valueRem: '8rem',
    description: 'Espaçamento estrutural de alta escala para layouts de página.',
  },
  {
    name: 'Spacing 2000',
    variable: '--spacing-2000',
    valuePx: 160,
    valueRem: '10rem',
    description: 'Espaçamento máximo para separações de grande amplitude visual.',
  },
  {
    name: 'Spacing 2400',
    variable: '--spacing-2400',
    valuePx: 192,
    valueRem: '12rem',
    description: 'Valor máximo da escala. Reservado para espaçamentos de nível de layout global.',
  },
]
